### ISSUE TITLE
AgoraKit installation 

### ISSUE THREAD

**Issue by Kayoku** [philippejadin/agorakit#205]
Hi,

First, I want to thank you for this project, it's pretty awesome. Look very interesting for my needs.

I'm trying to install AgoraKit on a ovh VPS in order to test it. After few hours of configuration, it finally works, but some problems persist and I needed to do some ugly thing for make it work.

Actually, I can access the home page of my AgoraKit instance (ex: http://fake-url.ovh/) but if I try to go for example on (ex: http://fake-url.ovh/groups) , it return me a 404 error.

If you are using nginx as a web server, can u provide me your .conf ?

I'll try to improve your Installation guide for the configuration stuff (for making the installation faster) and maybe dockerize the AgoraKit, if you are interested in.

Thank again for this useful tool :D !

PS: About nginx, I'm just asking because I need to leave right now and it's pretty annoying to leave without solving all the bugs. Anyway, I will probably fix it tomorrow.

**Comment by philippejadin** [comment]
Thank you for the nice feedback! 
Unfortunately I don't have experience with nginx. You can find a lot of information I guess since the underlying framework (laravel) is often used with nginx.
At least here : https://laravel.com/docs/5.7/installation#pretty-urls
and here : https://medium.com/@asked_io/how-to-install-php-7-2-x-nginx-1-10-x-laravel-5-6-f9e30ee30eff

...I see some clues :-)

A dockerized version and more docs are very much welcome, thank you in advance for contributing!

**Comment by Kayoku** [comment]
Hey,

Thx for the first link! I was just missing this `/index.php?$query_string` in my nginx config

```
location / {
    try_files $uri $uri/ /index.php?$query_string;
}
```
Perfect so ! Have a nice week :)
